### ISSUE TITLE
Добавте прикол

### ISSUE THREAD

**Issue by ayndqy** [sgorrister/flashsmoke#2]
якійсь смішний

**Comment by sgorrister** [comment]
Вибачте, це серйозний проєкт і я хочу мати хорошу оцінку, не думаю що це оцінийть мій викладач, тому приколів не буде, хіба що ви можете запропонувати прикол який буде доречним та відповідатиме темі проєкту.

Ви можете запропонувати мені свої приколи про Java і я розгляну їх

**Comment by ayndqy** [comment]
пропоную смішний прикол якісь
додайте його будь ласка

**Comment by sgorrister** [comment]
Вибачте, ви не надали ніякої конкретики.
Надайте свої пропозиції я буду готовий їх рохглянути

**Comment by ayndqy** [comment]
нє ну я типу маю на увазі конкретно смішний прикрл

**Comment by sgorrister** [comment]
Вибачте я вас не розумію.

**Comment by ayndqy** [comment]
😭😭😭

**Comment by sgorrister** [comment]
Приколів не буде.
